package de.avatarGeneratorV1.Main;

import java.awt.Color;
import java.awt.Component;
import java.awt.Desktop;
import java.awt.geom.RoundRectangle2D;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author sgtesuark
 */
public class mainFrame extends javax.swing.JFrame {

    public static BufferedImage getScreenshot(Component component) {
        BufferedImage image = new BufferedImage(component.getWidth(), component.getHeight(), BufferedImage.TYPE_INT_RGB);
        component.paint(image.getGraphics());
        return image;
    }

    public static void SaveScreenShot(Component component, String filename) throws Exception {
        BufferedImage img = getScreenshot(component);
        ImageIO.write(img, "png", new File(filename));
    }

    public static void infoBox(String infoMessage, String titleBar) {
        ImageIcon dialogsuccessicon = new ImageIcon("checkmark.png");
        JOptionPane.showMessageDialog(null, infoMessage, titleBar, JOptionPane.INFORMATION_MESSAGE, dialogsuccessicon);
    }

    public static void errorBox(String infoMessage, String titleBar) {
        ImageIcon dialogerroricon = new ImageIcon("xmark.png");
        JOptionPane.showMessageDialog(null, infoMessage, titleBar, JOptionPane.ERROR_MESSAGE, dialogerroricon);
    }

    /**
     * Creates new form jFrame
     */
    public mainFrame() {
        initComponents();
        setLocationRelativeTo(null);
        setShape(new RoundRectangle2D.Double(0, 0, 958, 575, 30, 30));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contentPanel = new javax.swing.JPanel();
        topPanel = new javax.swing.JPanel();
        jPanelClose = new javax.swing.JPanel();
        jLabelClose = new javax.swing.JLabel();
        jPanelMinimize = new javax.swing.JPanel();
        jLabelMinimize = new javax.swing.JLabel();
        jLabelIcon = new javax.swing.JLabel();
        jLabelTitel = new javax.swing.JLabel();
        imagePanel = new javax.swing.JPanel();
        Smoking = new javax.swing.JLabel();
        Goggle = new javax.swing.JLabel();
        Mask = new javax.swing.JLabel();
        Beard = new javax.swing.JLabel();
        Necklace = new javax.swing.JLabel();
        Headphones = new javax.swing.JLabel();
        Hat = new javax.swing.JLabel();
        Hair = new javax.swing.JLabel();
        Earring = new javax.swing.JLabel();
        Shirt = new javax.swing.JLabel();
        Skin = new javax.swing.JLabel();
        menuPanel = new javax.swing.JPanel();
        jLabelSkincolor = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabelSmoking = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        lableGoggle = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabelBeard = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jLabelHair = new javax.swing.JLabel();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jLabelHat = new javax.swing.JLabel();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jLabelEarring = new javax.swing.JLabel();
        jButtonToggleEarring = new javax.swing.JButton();
        jLabelMask = new javax.swing.JLabel();
        jButtonToggleMask = new javax.swing.JButton();
        jLabelBeautyspot = new javax.swing.JLabel();
        jButtonToggleBeautyspot = new javax.swing.JButton();
        jButtonRandomizer = new javax.swing.JButton();
        jLabelHeadphones = new javax.swing.JLabel();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jLabelHeadphones1 = new javax.swing.JLabel();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButtonSaveAsPNG = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(964, 593));
        setMinimumSize(new java.awt.Dimension(964, 593));
        setUndecorated(true);
        setResizable(false);

        contentPanel.setBackground(new java.awt.Color(20, 20, 20));
        contentPanel.setMaximumSize(new java.awt.Dimension(964, 575));
        contentPanel.setMinimumSize(new java.awt.Dimension(964, 575));

        topPanel.setBackground(java.awt.Color.black);
        topPanel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                topPanelMouseDragged(evt);
            }
        });
        topPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                topPanelMousePressed(evt);
            }
        });

        jPanelClose.setBackground(java.awt.Color.black);
        jPanelClose.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanelClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelCloseMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanelCloseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanelCloseMouseExited(evt);
            }
        });

        jLabelClose.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        jLabelClose.setForeground(java.awt.Color.gray);
        jLabelClose.setText("X");

        javax.swing.GroupLayout jPanelCloseLayout = new javax.swing.GroupLayout(jPanelClose);
        jPanelClose.setLayout(jPanelCloseLayout);
        jPanelCloseLayout.setHorizontalGroup(
            jPanelCloseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCloseLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelClose)
                .addContainerGap())
        );
        jPanelCloseLayout.setVerticalGroup(
            jPanelCloseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCloseLayout.createSequentialGroup()
                .addComponent(jLabelClose)
                .addGap(0, 0, 0))
        );

        jPanelMinimize.setBackground(java.awt.Color.black);
        jPanelMinimize.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanelMinimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelMinimizeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanelMinimizeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanelMinimizeMouseExited(evt);
            }
        });

        jLabelMinimize.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabelMinimize.setForeground(java.awt.Color.gray);
        jLabelMinimize.setText("–");

        javax.swing.GroupLayout jPanelMinimizeLayout = new javax.swing.GroupLayout(jPanelMinimize);
        jPanelMinimize.setLayout(jPanelMinimizeLayout);
        jPanelMinimizeLayout.setHorizontalGroup(
            jPanelMinimizeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMinimizeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelMinimize)
                .addContainerGap(11, Short.MAX_VALUE))
        );
        jPanelMinimizeLayout.setVerticalGroup(
            jPanelMinimizeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMinimizeLayout.createSequentialGroup()
                .addComponent(jLabelMinimize)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jLabelIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/avatarGeneratorV1/images/icon.png"))); // NOI18N
        jLabelIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelIconMouseClicked(evt);
            }
        });

        jLabelTitel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelTitel.setForeground(java.awt.Color.white);
        jLabelTitel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitel.setText("Avatar Generator V1");

        javax.swing.GroupLayout topPanelLayout = new javax.swing.GroupLayout(topPanel);
        topPanel.setLayout(topPanelLayout);
        topPanelLayout.setHorizontalGroup(
            topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, topPanelLayout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jLabelIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelTitel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanelMinimize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanelClose, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6))
        );
        topPanelLayout.setVerticalGroup(
            topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topPanelLayout.createSequentialGroup()
                .addGroup(topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelMinimize, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelTitel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(topPanelLayout.createSequentialGroup()
                        .addComponent(jPanelClose, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jLabelIcon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        imagePanel.setBackground(java.awt.Color.gray);
        imagePanel.setPreferredSize(new java.awt.Dimension(442, 442));
        imagePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Smoking.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Smoking.setMaximumSize(new java.awt.Dimension(442, 442));
        Smoking.setMinimumSize(new java.awt.Dimension(442, 442));
        Smoking.setPreferredSize(new java.awt.Dimension(442, 442));
        imagePanel.add(Smoking, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
        imagePanel.add(Goggle, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
        imagePanel.add(Mask, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
        imagePanel.add(Beard, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
        imagePanel.add(Necklace, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
        imagePanel.add(Headphones, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
        imagePanel.add(Hat, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
        imagePanel.add(Hair, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
        imagePanel.add(Earring, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
        imagePanel.add(Shirt, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        Skin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Skin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/avatarGeneratorV1/images/assets/Skin/Skin1.png"))); // NOI18N
        imagePanel.add(Skin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        menuPanel.setBackground(new java.awt.Color(20, 20, 20));

        jLabelSkincolor.setFont(new java.awt.Font("Aharoni", 1, 18)); // NOI18N
        jLabelSkincolor.setForeground(java.awt.Color.white);
        jLabelSkincolor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelSkincolor.setText("Skincolor");

        jButton1.setText("←");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("→");
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabelSmoking.setFont(new java.awt.Font("Aharoni", 1, 18)); // NOI18N
        jLabelSmoking.setForeground(java.awt.Color.white);
        jLabelSmoking.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelSmoking.setText("Smoking");

        jButton3.setText("←");
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("→");
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        lableGoggle.setFont(new java.awt.Font("Aharoni", 1, 18)); // NOI18N
        lableGoggle.setForeground(java.awt.Color.white);
        lableGoggle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lableGoggle.setText("Goggle");

        jButton5.setText("←");
        jButton5.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("→");
        jButton6.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jLabelBeard.setFont(new java.awt.Font("Aharoni", 1, 18)); // NOI18N
        jLabelBeard.setForeground(java.awt.Color.white);
        jLabelBeard.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelBeard.setText("Beard");

        jButton7.setText("←");
        jButton7.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setText("→");
        jButton8.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jLabelHair.setFont(new java.awt.Font("Aharoni", 1, 18)); // NOI18N
        jLabelHair.setForeground(java.awt.Color.white);
        jLabelHair.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelHair.setText("Hair");

        jButton9.setText("←");
        jButton9.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton10.setText("→");
        jButton10.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jLabelHat.setFont(new java.awt.Font("Aharoni", 1, 18)); // NOI18N
        jLabelHat.setForeground(java.awt.Color.white);
        jLabelHat.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelHat.setText("Hat");

        jButton11.setText("←");
        jButton11.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        jButton12.setText("→");
        jButton12.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        jLabelEarring.setFont(new java.awt.Font("Aharoni", 1, 18)); // NOI18N
        jLabelEarring.setForeground(java.awt.Color.white);
        jLabelEarring.setText("Earring");

        jButtonToggleEarring.setText("OFF");
        jButtonToggleEarring.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButtonToggleEarring.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonToggleEarringActionPerformed(evt);
            }
        });

        jLabelMask.setFont(new java.awt.Font("Aharoni", 1, 18)); // NOI18N
        jLabelMask.setForeground(java.awt.Color.white);
        jLabelMask.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelMask.setText("Mask");

        jButtonToggleMask.setText("OFF");
        jButtonToggleMask.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButtonToggleMask.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonToggleMaskActionPerformed(evt);
            }
        });

        jLabelBeautyspot.setFont(new java.awt.Font("Aharoni", 1, 18)); // NOI18N
        jLabelBeautyspot.setForeground(java.awt.Color.white);
        jLabelBeautyspot.setText("Necklace");

        jButtonToggleBeautyspot.setText("OFF");
        jButtonToggleBeautyspot.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButtonToggleBeautyspot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonToggleBeautyspotActionPerformed(evt);
            }
        });

        jButtonRandomizer.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonRandomizer.setText("Randomize");
        jButtonRandomizer.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButtonRandomizer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRandomizerActionPerformed(evt);
            }
        });

        jLabelHeadphones.setFont(new java.awt.Font("Aharoni", 1, 18)); // NOI18N
        jLabelHeadphones.setForeground(java.awt.Color.white);
        jLabelHeadphones.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelHeadphones.setText("Headphones");

        jButton13.setText("←");
        jButton13.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });

        jButton14.setText("→");
        jButton14.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });

        jLabelHeadphones1.setFont(new java.awt.Font("Aharoni", 1, 18)); // NOI18N
        jLabelHeadphones1.setForeground(java.awt.Color.white);
        jLabelHeadphones1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelHeadphones1.setText("Shirt");

        jButton15.setText("←");
        jButton15.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });

        jButton16.setText("→");
        jButton16.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout menuPanelLayout = new javax.swing.GroupLayout(menuPanel);
        menuPanel.setLayout(menuPanelLayout);
        menuPanelLayout.setHorizontalGroup(
            menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuPanelLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelEarring, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonToggleEarring, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(73, 73, 73)
                .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelMask, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonToggleMask))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuPanelLayout.createSequentialGroup()
                        .addComponent(jButtonToggleBeautyspot)
                        .addGap(59, 59, 59))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuPanelLayout.createSequentialGroup()
                        .addComponent(jLabelBeautyspot)
                        .addGap(46, 46, 46))))
            .addGroup(menuPanelLayout.createSequentialGroup()
                .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(menuPanelLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(menuPanelLayout.createSequentialGroup()
                                    .addComponent(jButton5)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jButton6))
                                .addComponent(jLabelSkincolor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lableGoggle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(menuPanelLayout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton2)))
                        .addGap(124, 124, 124)
                        .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelBeard, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(menuPanelLayout.createSequentialGroup()
                                .addComponent(jButton7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton8))
                            .addComponent(jLabelSmoking, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(menuPanelLayout.createSequentialGroup()
                                .addComponent(jButton3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton4))))
                    .addGroup(menuPanelLayout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addComponent(jButtonRandomizer, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(menuPanelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(menuPanelLayout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(menuPanelLayout.createSequentialGroup()
                                        .addComponent(jButton13)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton14))
                                    .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(menuPanelLayout.createSequentialGroup()
                                            .addComponent(jButton9)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jButton10))
                                        .addComponent(jLabelHair, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jLabelHeadphones, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(menuPanelLayout.createSequentialGroup()
                                .addComponent(jButton11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton12))
                            .addComponent(jLabelHat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(menuPanelLayout.createSequentialGroup()
                                .addComponent(jButton15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton16))
                            .addComponent(jLabelHeadphones1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(63, Short.MAX_VALUE))
        );
        menuPanelLayout.setVerticalGroup(
            menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuPanelLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(menuPanelLayout.createSequentialGroup()
                        .addComponent(jLabelSkincolor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(jButton2))
                        .addGap(34, 34, 34)
                        .addComponent(lableGoggle)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton5)
                            .addComponent(jButton6)))
                    .addGroup(menuPanelLayout.createSequentialGroup()
                        .addComponent(jLabelSmoking)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton3)
                            .addComponent(jButton4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelBeard)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton7)
                            .addComponent(jButton8))))
                .addGap(34, 34, 34)
                .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(menuPanelLayout.createSequentialGroup()
                        .addComponent(jLabelHat)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton11)
                            .addComponent(jButton12)))
                    .addGroup(menuPanelLayout.createSequentialGroup()
                        .addComponent(jLabelHair)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton9)
                            .addComponent(jButton10))))
                .addGap(34, 34, 34)
                .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(menuPanelLayout.createSequentialGroup()
                        .addComponent(jLabelHeadphones)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton13)
                            .addComponent(jButton14)))
                    .addGroup(menuPanelLayout.createSequentialGroup()
                        .addComponent(jLabelHeadphones1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton15)
                            .addComponent(jButton16))))
                .addGap(37, 37, 37)
                .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(menuPanelLayout.createSequentialGroup()
                        .addComponent(jLabelEarring)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonToggleEarring))
                    .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(menuPanelLayout.createSequentialGroup()
                            .addComponent(jLabelBeautyspot)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButtonToggleBeautyspot))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, menuPanelLayout.createSequentialGroup()
                            .addComponent(jLabelMask)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButtonToggleMask))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(jButtonRandomizer, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        jButtonSaveAsPNG.setText("Save as .png file");
        jButtonSaveAsPNG.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButtonSaveAsPNG.setPreferredSize(new java.awt.Dimension(99, 25));
        jButtonSaveAsPNG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSaveAsPNGActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout contentPanelLayout = new javax.swing.GroupLayout(contentPanel);
        contentPanel.setLayout(contentPanelLayout);
        contentPanelLayout.setHorizontalGroup(
            contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(topPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(contentPanelLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(menuPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(contentPanelLayout.createSequentialGroup()
                        .addGap(185, 185, 185)
                        .addComponent(jButtonSaveAsPNG, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(contentPanelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(imagePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 462, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        contentPanelLayout.setVerticalGroup(
            contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentPanelLayout.createSequentialGroup()
                .addComponent(topPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addGroup(contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(contentPanelLayout.createSequentialGroup()
                        .addComponent(imagePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonSaveAsPNG, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(menuPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(contentPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(contentPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    int skin = 0;
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (skin >= 1) {
            skin--;
        }
        switch (skin) {
            case 0:
                Skin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/avatarGeneratorV1/images/assets/Skin/Skin1.png")));
                break;
            case 1:
                Skin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/avatarGeneratorV1/images/assets/Skin/Skin2.png")));
                break;
            case 2:
                Skin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/avatarGeneratorV1/images/assets/Skin/Skin3.png")));
                break;
            case 3:
                Skin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/avatarGeneratorV1/images/assets/Skin/Skin4.png")));
                break;
            case 4:
                Skin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/avatarGeneratorV1/images/assets/Skin/Skin5.png")));
                break;
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if (skin <= 3) {
            skin++;
        }
        switch (skin) {
            case 0:
                Skin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/avatarGeneratorV1/images/assets/Skin/Skin1.png")));
                break;
            case 1:
                Skin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/avatarGeneratorV1/images/assets/Skin/Skin2.png")));
                break;
            case 2:
                Skin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/avatarGeneratorV1/images/assets/Skin/Skin3.png")));
                break;
            case 3:
                Skin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/avatarGeneratorV1/images/assets/Skin/Skin4.png")));
                break;
            case 4:
                Skin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/avatarGeneratorV1/images/assets/Skin/Skin5.png")));
                break;
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    int smoking;
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        if (smoking >= 1) {
            smoking--;
        }
        switch (smoking) {
            case 0:
                Smoking.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/avatarGeneratorV1/images/assets/empty.png")));
                break;
            case 1:
                Smoking.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/avatarGeneratorV1/images/assets/Rauchen/Smoking1.png")));
                break;
            case 2:
                Smoking.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/avatarGeneratorV1/images/assets/Rauchen/Smoking2.png")));
                break;
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        if (smoking <= 1) {
            smoking++;
        }
        switch (smoking) {
            case 0:
                Smoking.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/avatarGeneratorV1/images/assets/empty.png")));
                break;
            case 1:
                Smoking.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/avatarGeneratorV1/images/assets/Rauchen/Smoking1.png")));
                break;
            case 2:
                Smoking.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/avatarGeneratorV1/images/assets/Rauchen/Smoking2.png")));
                break;
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    int goggle = 0;
    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        if (goggle >= 1) {
            goggle--;
        }
        switch (goggle) {
            case 0:
                Goggle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/avatarGeneratorV1/images/assets/empty.png")));
                break;
            case 1:
                Goggle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/avatarGeneratorV1/images/assets/Brille/Brille1.png")));
                break;
            case 2:
                Goggle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/avatarGeneratorV1/images/assets/Brille/Brille2.png")));
                break;
            case 3:
                Goggle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/avatarGeneratorV1/images/assets/Brille/Brille3.png")));
                break;
            case 4:
                Goggle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/avatarGeneratorV1/images/assets/Brille/Brille4.png")));
                break;
            case 5:
                Goggle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/avatarGeneratorV1/images/assets/Brille/Brille5.png")));
                break;
            case 6:
                Goggle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/avatarGeneratorV1/images/assets/Brille/Brille6.png")));
                break;
            case 7:
                Goggle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/avatarGeneratorV1/images/assets/Brille/Brille7.png")));
                break;
            case 8:
                Goggle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/avatarGeneratorV1/images/assets/Brille/Brille8.png")));
                break;
            case 9:
                Goggle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/avatarGeneratorV1/images/assets/Brille/Brille9.png")));
                break;
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        if (goggle <= 8) {
            goggle++;
        }
        switch (goggle) {
            case 0:
                Goggle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/avatarGeneratorV1/images/assets/empty.png")));
                break;
            case 1:
                Goggle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/avatarGeneratorV1/images/assets/Brille/Brille1.png")));
                break;
            case 2:
                Goggle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/avatarGeneratorV1/images/assets/Brille/Brille2.png")));
                break;
            case 3:
                Goggle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/avatarGeneratorV1/images/assets/Brille/Brille3.png")));
                break;
            case 4:
                Goggle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/avatarGeneratorV1/images/assets/Brille/Brille4.png")));
                break;
            case 5:
                Goggle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/avatarGeneratorV1/images/assets/Brille/Brille5.png")));
                break;
            case 6:
                Goggle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/avatarGeneratorV1/images/assets/Brille/Brille6.png")));
                break;
            case 7:
                Goggle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/avatarGeneratorV1/images/assets/Brille/Brille7.png")));
                break;
            case 8:
                Goggle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/avatarGeneratorV1/images/assets/Brille/Brille8.png")));
                break;
            case 9:
                Goggle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/avatarGeneratorV1/images/assets/Brille/Brille9.png")));
                break;
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    int beard = 0;
    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        if (beard >= 1) {
            beard--;
        }
        switch (beard) {
            case 0:
                Beard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/avatarGeneratorV1/images/assets/empty.png")));
                break;
            case 1:
                Beard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/avatarGeneratorV1/images/assets/Bart/Bart1.png")));
                break;
            case 2:
                Beard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/avatarGeneratorV1/images/assets/Bart/Bart2.png")));
                break;
            case 3:
                Beard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/avatarGeneratorV1/images/assets/Bart/Bart3.png")));
                break;
            case 4:
                Beard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/avatarGeneratorV1/images/assets/Bart/Bart4.png")));
                break;
            case 5:
                Beard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/avatarGeneratorV1/images/assets/Bart/Bart5.png")));
                break;
            case 6:
                Beard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/avatarGeneratorV1/images/assets/Bart/Bart6.png")));
                break;
            case 7:
                Beard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/avatarGeneratorV1/images/assets/Bart/Bart7.png")));
                break;
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        if (beard <= 6) {
            beard++;
        }
        switch (beard) {
            case 0:
                Beard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/avatarGeneratorV1/images/assets/empty.png")));
                break;
            case 1:
                Beard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/avatarGeneratorV1/images/assets/Bart/Bart1.png")));
                break;
            case 2:
                Beard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/avatarGeneratorV1/images/assets/Bart/Bart2.png")));
                break;
            case 3:
                Beard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/avatarGeneratorV1/images/assets/Bart/Bart3.png")));
                break;
            case 4:
                Beard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/avatarGeneratorV1/images/assets/Bart/Bart4.png")));
                break;
            case 5:
                Beard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/avatarGeneratorV1/images/assets/Bart/Bart5.png")));
                break;
            case 6:
                Beard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/avatarGeneratorV1/images/assets/Bart/Bart6.png")));
                break;
            case 7:
                Beard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/avatarGeneratorV1/images/assets/Bart/Bart7.png")));
                break;
        }
    }//GEN-LAST:event_jButton8ActionPerformed

    int hair = 0;
    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        if (hair >= 1) {
            hair--;
        }
        switch (hair) {
            case 0:
                Hair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/avatarGeneratorV1/images/assets/empty.png")));
                break;
            case 1:
                Hair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/avatarGeneratorV1/images/assets/Haare/Haare1.png")));
                break;
            case 2:
                Hair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/avatarGeneratorV1/images/assets/Haare/Haare2.png")));
                break;
        }
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        if (hair <= 1) {
            hair++;
        }
        switch (hair) {
            case 0:
                Hair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/avatarGeneratorV1/images/assets/empty.png")));
                break;
            case 1:
                Hair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/avatarGeneratorV1/images/assets/Haare/Haare1.png")));
                break;
            case 2:
                Hair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/avatarGeneratorV1/images/assets/Haare/Haare2.png")));
                break;
        }
    }//GEN-LAST:event_jButton10ActionPerformed

    int hat = 0;
    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        if (hat >= 1) {
            hat--;
        }
        switch (hat) {
            case 0:
                Hat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/avatarGeneratorV1/images/assets/empty.png")));
                break;
            case 1:
                Hat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/avatarGeneratorV1/images/assets/Kopfbedeckung/Hat1.png")));
                break;
            case 2:
                Hat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/avatarGeneratorV1/images/assets/Kopfbedeckung/Hat2.png")));
                break;
            case 3:
                Hat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/avatarGeneratorV1/images/assets/Kopfbedeckung/Hat3.png")));
                break;
            case 4:
                Hat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/avatarGeneratorV1/images/assets/Kopfbedeckung/Hat4.png")));
                break;
            case 5:
                Hat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/avatarGeneratorV1/images/assets/Kopfbedeckung/Hat5.png")));
                break;
            case 6:
                Hat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/avatarGeneratorV1/images/assets/Kopfbedeckung/Hat6.png")));
                break;
            case 7:
                Hat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/avatarGeneratorV1/images/assets/Kopfbedeckung/Hat7.png")));
                break;
            case 8:
                Hat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/avatarGeneratorV1/images/assets/Kopfbedeckung/Hat8.png")));
                break;
            case 9:
                Hat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/avatarGeneratorV1/images/assets/Kopfbedeckung/Hat9.png")));
                break;
        }
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        if (hat <= 8) {
            hat++;
        }
        switch (hat) {
            case 0:
                Hat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/avatarGeneratorV1/images/assets/empty.png")));
                break;
            case 1:
                Hat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/avatarGeneratorV1/images/assets/Kopfbedeckung/Hat1.png")));
                break;
            case 2:
                Hat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/avatarGeneratorV1/images/assets/Kopfbedeckung/Hat2.png")));
                break;
            case 3:
                Hat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/avatarGeneratorV1/images/assets/Kopfbedeckung/Hat3.png")));
                break;
            case 4:
                Hat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/avatarGeneratorV1/images/assets/Kopfbedeckung/Hat4.png")));
                break;
            case 5:
                Hat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/avatarGeneratorV1/images/assets/Kopfbedeckung/Hat5.png")));
                break;
            case 6:
                Hat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/avatarGeneratorV1/images/assets/Kopfbedeckung/Hat6.png")));
                break;
            case 7:
                Hat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/avatarGeneratorV1/images/assets/Kopfbedeckung/Hat7.png")));
                break;
            case 8:
                Hat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/avatarGeneratorV1/images/assets/Kopfbedeckung/Hat8.png")));
                break;
            case 9:
                Hat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/avatarGeneratorV1/images/assets/Kopfbedeckung/Hat9.png")));
                break;
        }
    }//GEN-LAST:event_jButton12ActionPerformed

    int headphones = 0;
    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        if (headphones >= 1) {
            headphones--;
        }
        switch (headphones) {
            case 0:
                Headphones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/avatarGeneratorV1/images/assets/empty.png")));
                break;
            case 1:
                Headphones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/avatarGeneratorV1/images/assets/Kopfhoerer/Headphone1.png")));
                break;
            case 2:
                Headphones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/avatarGeneratorV1/images/assets/Kopfhoerer/Headphone2.png")));
                break;
        }
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        if (headphones <= 1) {
            headphones++;
        }
        switch (headphones) {
            case 0:
                Headphones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/avatarGeneratorV1/images/assets/empty.png")));
                break;
            case 1:
                Headphones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/avatarGeneratorV1/images/assets/Kopfhoerer/Headphone1.png")));
                break;
            case 2:
                Headphones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/avatarGeneratorV1/images/assets/Kopfhoerer/Headphone2.png")));
                break;
        }
    }//GEN-LAST:event_jButton14ActionPerformed

    int shirt = 0;
    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        if (shirt >= 1) {
            shirt--;
        }
        switch (shirt) {
            case 0:
                Shirt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/avatarGeneratorV1/images/assets/empty.png")));
                Hat.setVisible(true);
                break;
            case 1:
                Shirt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/avatarGeneratorV1/images/assets/Shirts/Shirt1.png")));
                Hat.setVisible(true);
                break;
            case 2:
                Shirt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/avatarGeneratorV1/images/assets/Shirts/Shirt2.png")));
                Hat.setVisible(true);
                break;
            case 3:
                Shirt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/avatarGeneratorV1/images/assets/Shirts/Shirt3.png")));
                Hat.setVisible(true);
                break;
            case 4:
                Shirt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/avatarGeneratorV1/images/assets/Shirts/Shirt4.png")));
                Hat.setVisible(true);
                break;
            case 5:
                Shirt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/avatarGeneratorV1/images/assets/Shirts/Shirt5.png")));
                Hat.setVisible(false);
                break;
        }
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {
        if (shirt <= 4) {
            shirt++;
        }
        switch (shirt) {
            case 0:
                Shirt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/avatarGeneratorV1/images/assets/empty.png")));
                Hat.setVisible(true);
                break;
            case 1:
                Shirt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/avatarGeneratorV1/images/assets/Shirts/Shirt1.png")));
                Hat.setVisible(true);
                break;
            case 2:
                Shirt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/avatarGeneratorV1/images/assets/Shirts/Shirt2.png")));
                Hat.setVisible(true);
                break;
            case 3:
                Shirt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/avatarGeneratorV1/images/assets/Shirts/Shirt3.png")));
                Hat.setVisible(true);
                break;
            case 4:
                Shirt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/avatarGeneratorV1/images/assets/Shirts/Shirt4.png")));
                Hat.setVisible(true);
                break;
            case 5:
                Shirt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/avatarGeneratorV1/images/assets/Shirts/Shirt5.png")));
                Hat.setVisible(false);
                break;
        }
    }
    private int tx, ty;
    private void topPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_topPanelMousePressed
        {
            tx = evt.getX();
            ty = evt.getY();
        }
    }//GEN-LAST:event_topPanelMousePressed

    private void topPanelMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_topPanelMouseDragged
        {
            this.setLocation(evt.getXOnScreen() - tx, evt.getYOnScreen() - ty);
        }
    }//GEN-LAST:event_topPanelMouseDragged

    private void jButtonToggleEarringActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonToggleEarringActionPerformed
        if (jButtonToggleEarring.getText().equals("OFF")) {
            jButtonToggleEarring.setText(" ON ");
            Earring.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/avatarGeneratorV1/images/assets/Schmuck/Ohrring.png")));
        } else {
            jButtonToggleEarring.setText("OFF");
            Earring.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/avatarGeneratorV1/images/assets/empty.png")));
        }
    }//GEN-LAST:event_jButtonToggleEarringActionPerformed

    private void jButtonToggleMaskActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonToggleMaskActionPerformed
        if (jButtonToggleMask.getText().equals("OFF")) {
            jButtonToggleMask.setText(" ON ");
            Mask.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/avatarGeneratorV1/images/assets/Maske/Maske.png")));
            Smoking.setVisible(false);
        } else {
            jButtonToggleMask.setText("OFF");
            Mask.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/avatarGeneratorV1/images/assets/empty.png")));
            Smoking.setVisible(true);
        }
    }//GEN-LAST:event_jButtonToggleMaskActionPerformed

    private void jButtonToggleBeautyspotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonToggleBeautyspotActionPerformed
        if (jButtonToggleBeautyspot.getText().equals("OFF")) {
            jButtonToggleBeautyspot.setText(" ON ");
            Necklace.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/avatarGeneratorV1/images/assets/Schmuck/Kette.png")));
        } else {
            jButtonToggleBeautyspot.setText("OFF");
            Necklace.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/avatarGeneratorV1/images/assets/empty.png")));
        }
    }//GEN-LAST:event_jButtonToggleBeautyspotActionPerformed

    private void jButtonSaveAsPNGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaveAsPNGActionPerformed
        int savesuccess = 0;
        try {
            JFileChooser chooser = new JFileChooser();
            chooser.setAcceptAllFileFilterUsed(false);
            FileNameExtensionFilter extFilter = new FileNameExtensionFilter("PNG (*.PNG)", "png");
            chooser.addChoosableFileFilter(extFilter);
            chooser.showSaveDialog(null);
            File f = chooser.getCurrentDirectory();
            String path = f.getAbsolutePath();
            String filename = chooser.getSelectedFile().getName();

            if (filename.endsWith(".png")) {
                SaveScreenShot(imagePanel, path + "\\" + filename);
                savesuccess = 1;
            } else {
                SaveScreenShot(imagePanel, path + "\\" + filename + ".png");
                savesuccess = 1;
            }
        } catch (Exception e) {
        }
        if (savesuccess == 1) {
            mainFrame.infoBox("Avatar successfully saved!", jLabelIcon.getText() + jLabelTitel.getText());
        } else {
            mainFrame.errorBox("Avatar could not be saved!", jLabelTitel.getText());
        }
        savesuccess = 0;
    }//GEN-LAST:event_jButtonSaveAsPNGActionPerformed

    private void jButtonRandomizerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRandomizerActionPerformed
        // SKIN
        int maxSkincolor = 1;
        int minSkincolor = 0;
        int rangeSkincolor = maxSkincolor - minSkincolor + 1;

        skin = (int) (Math.random() * rangeSkincolor) + minSkincolor;
        // Output
        switch (skin) {
            case 0:
                Skin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/avatarGeneratorV1/images/assets/Skin/Skin1.png")));
                break;
            case 1:
                Skin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/avatarGeneratorV1/images/assets/Skin/Skin2.png")));
                break;
        }

        // SMOKING
        int maxSmoking = 2;
        int minSmoking = 0;
        int rangeSmoking = maxSmoking - minSmoking + 1;

        smoking = (int) (Math.random() * rangeSmoking) + minSmoking;
        // Output
        switch (smoking) {
            case 0:
                Smoking.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/avatarGeneratorV1/images/assets/empty.png")));
                break;
            case 1:
                Smoking.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/avatarGeneratorV1/images/assets/Rauchen/Smoking1.png")));
                break;
            case 2:
                Smoking.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/avatarGeneratorV1/images/assets/Rauchen/Smoking2.png")));
                break;
        }

        // GOGGLE
        int maxGoggle = 9;
        int minGoggle = 0;
        int rangeGoggle = maxGoggle - minGoggle + 1;

        goggle = (int) (Math.random() * rangeGoggle) + minGoggle;
        // Output
        switch (goggle) {
            case 0:
                Goggle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/avatarGeneratorV1/images/assets/empty.png")));
                break;
            case 1:
                Goggle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/avatarGeneratorV1/images/assets/Brille/Brille1.png")));
                break;
            case 2:
                Goggle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/avatarGeneratorV1/images/assets/Brille/Brille2.png")));
                break;
            case 3:
                Goggle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/avatarGeneratorV1/images/assets/Brille/Brille3.png")));
                break;
            case 4:
                Goggle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/avatarGeneratorV1/images/assets/Brille/Brille4.png")));
                break;
            case 5:
                Goggle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/avatarGeneratorV1/images/assets/Brille/Brille5.png")));
                break;
            case 6:
                Goggle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/avatarGeneratorV1/images/assets/Brille/Brille6.png")));
                break;
            case 7:
                Goggle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/avatarGeneratorV1/images/assets/Brille/Brille7.png")));
                break;
            case 8:
                Goggle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/avatarGeneratorV1/images/assets/Brille/Brille8.png")));
                break;
            case 9:
                Goggle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/avatarGeneratorV1/images/assets/Brille/Brille9.png")));
                break;
        }   
        
        // Beard
        int maxBeard = 7;
        int minBeard = 0;
        int rangeBeard = maxBeard - minBeard + 1;

        beard = (int) (Math.random() * rangeBeard) + minBeard;
        // Output
        switch (beard) {
            case 0:
                Beard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/avatarGeneratorV1/images/assets/empty.png")));
                break;
            case 1:
                Beard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/avatarGeneratorV1/images/assets/Bart/Bart1.png")));
                break;
            case 2:
                Beard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/avatarGeneratorV1/images/assets/Bart/Bart2.png")));
                break;
            case 3:
                Beard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/avatarGeneratorV1/images/assets/Bart/Bart3.png")));
                break;
            case 4:
                Beard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/avatarGeneratorV1/images/assets/Bart/Bart4.png")));
                break;
            case 5:
                Beard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/avatarGeneratorV1/images/assets/Bart/Bart5.png")));
                break;
            case 6:
                Beard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/avatarGeneratorV1/images/assets/Bart/Bart6.png")));
                break;
            case 7:
                Beard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/avatarGeneratorV1/images/assets/Bart/Bart7.png")));
                break;
        } 

        // Hair
        int maxHair = 2;
        int minHair = 0;
        int rangeHair = maxHair - minHair + 1;

        hair = (int) (Math.random() * rangeHair) + minHair;
        // Output
        switch (hair) {
            case 0:
                Hair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/avatarGeneratorV1/images/assets/empty.png")));
                break;
            case 1:
                Hair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/avatarGeneratorV1/images/assets/Haare/Haare1.png")));
                break;
            case 2:
                Hair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/avatarGeneratorV1/images/assets/Haare/Haare2.png")));
                break; 
        } 
        
        // Hat
        int maxHat = 9;
        int minHat = 0;
        int rangeHat = maxHat - minHat + 1;

        hat = (int) (Math.random() * rangeHat) + minHat;
        // Output
        switch (hat) {
            case 0:
                Hat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/avatarGeneratorV1/images/assets/empty.png")));
                break;
            case 1:
                Hat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/avatarGeneratorV1/images/assets/Kopfbedeckung/Hat1.png")));
                break;
            case 2:
                Hat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/avatarGeneratorV1/images/assets/Kopfbedeckung/Hat2.png")));
                break;
            case 3:
                Hat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/avatarGeneratorV1/images/assets/Kopfbedeckung/Hat3.png")));
                break;
            case 4:
                Hat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/avatarGeneratorV1/images/assets/Kopfbedeckung/Hat4.png")));
                break;
            case 5:
                Hat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/avatarGeneratorV1/images/assets/Kopfbedeckung/Hat5.png")));
                break;
            case 6:
                Hat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/avatarGeneratorV1/images/assets/Kopfbedeckung/Hat6.png")));
                break;
            case 7:
                Hat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/avatarGeneratorV1/images/assets/Kopfbedeckung/Hat7.png")));
                break;
            case 8:
                Hat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/avatarGeneratorV1/images/assets/Kopfbedeckung/Hat8.png")));
                break;
            case 9:
                Hat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/avatarGeneratorV1/images/assets/Kopfbedeckung/Hat9.png")));
                break;
        }
        
        // Headphones
        int maxHeadphones = 7;
        int minHeadphones = 0;
        int rangeHeadphones = maxHeadphones - minHeadphones + 1;

        headphones = (int) (Math.random() * rangeHeadphones) + minHeadphones;
        // Output
        switch (headphones) {
            case 0:
                Headphones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/avatarGeneratorV1/images/assets/empty.png")));
                break;
            case 1:
                Headphones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/avatarGeneratorV1/images/assets/Kopfhoerer/Headphone1.png")));
                break;
            case 2:
                Headphones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/avatarGeneratorV1/images/assets/Kopfhoerer/Headphone2.png")));
                break;
            case 3:
                headphones = 0;
                Headphones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/avatarGeneratorV1/images/assets/empty.png")));
                break;
            case 4:
                headphones = 0;
                Headphones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/avatarGeneratorV1/images/assets/empty.png")));
                break;
            case 5:
                headphones = 0;
                Headphones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/avatarGeneratorV1/images/assets/empty.png")));
                break;
            case 6:
                headphones = 0;
                Headphones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/avatarGeneratorV1/images/assets/empty.png")));
                break;
            case 7:
                headphones = 0;
                Headphones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/avatarGeneratorV1/images/assets/empty.png")));
                break;
        }
        
        // Shirt
        int maxShirt = 5;
        int minShirt = 0;
        int rangeShirt = maxShirt - minShirt + 1;

        shirt = (int) (Math.random() * rangeShirt) + minShirt;
        // Output
        switch (shirt) {
            case 0:
                Shirt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/avatarGeneratorV1/images/assets/empty.png")));
                Hat.setVisible(true);
                break;
            case 1:
                Shirt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/avatarGeneratorV1/images/assets/Shirts/Shirt1.png")));
                Hat.setVisible(true);
                break;
            case 2:
                Shirt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/avatarGeneratorV1/images/assets/Shirts/Shirt2.png")));
                Hat.setVisible(true);
                break;
            case 3:
                Shirt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/avatarGeneratorV1/images/assets/Shirts/Shirt3.png")));
                Hat.setVisible(true);
                break;
            case 4:
                Shirt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/avatarGeneratorV1/images/assets/Shirts/Shirt4.png")));
                Hat.setVisible(true);
                break;
            case 5:
                Shirt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/avatarGeneratorV1/images/assets/Shirts/Shirt5.png")));
                Hat.setVisible(false);
                break;
        }
    }//GEN-LAST:event_jButtonRandomizerActionPerformed

    private void jPanelCloseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelCloseMouseEntered
        this.jPanelClose.setBackground(Color.RED);
        this.jLabelClose.setForeground(Color.WHITE);
    }//GEN-LAST:event_jPanelCloseMouseEntered

    private void jPanelCloseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelCloseMouseExited
        this.jPanelClose.setBackground(Color.BLACK);
        this.jLabelClose.setForeground(Color.GRAY);
    }//GEN-LAST:event_jPanelCloseMouseExited

    private void jPanelMinimizeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelMinimizeMouseEntered
        this.jPanelMinimize.setBackground(Color.DARK_GRAY);
        this.jLabelMinimize.setForeground(Color.WHITE);
    }//GEN-LAST:event_jPanelMinimizeMouseEntered

    private void jPanelMinimizeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelMinimizeMouseExited
        this.jPanelMinimize.setBackground(Color.BLACK);
        this.jLabelMinimize.setForeground(Color.GRAY);
    }//GEN-LAST:event_jPanelMinimizeMouseExited

    private void jPanelCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelCloseMouseClicked
        System.exit(0);
    }//GEN-LAST:event_jPanelCloseMouseClicked

    private void jPanelMinimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelMinimizeMouseClicked
        this.setState(mainFrame.ICONIFIED);
    }//GEN-LAST:event_jPanelMinimizeMouseClicked

    int easteregg = 0;
    private void jLabelIconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelIconMouseClicked
        easteregg++;
        if (easteregg == 7) {
            try {
                Desktop.getDesktop().browse(new URI("https://www.youtube.com/watch?v=dQw4w9WgXcQ"));
            } catch (URISyntaxException ex) {
                Logger.getLogger(mainFrame.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(mainFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
            easteregg = 0;
        }
    }//GEN-LAST:event_jLabelIconMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Windows look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Beard;
    private javax.swing.JLabel Earring;
    private javax.swing.JLabel Goggle;
    private javax.swing.JLabel Hair;
    private javax.swing.JLabel Hat;
    private javax.swing.JLabel Headphones;
    private javax.swing.JLabel Mask;
    private javax.swing.JLabel Necklace;
    private javax.swing.JLabel Shirt;
    private javax.swing.JLabel Skin;
    private javax.swing.JLabel Smoking;
    private javax.swing.JPanel contentPanel;
    private javax.swing.JPanel imagePanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JButton jButtonRandomizer;
    private javax.swing.JButton jButtonSaveAsPNG;
    private javax.swing.JButton jButtonToggleBeautyspot;
    private javax.swing.JButton jButtonToggleEarring;
    private javax.swing.JButton jButtonToggleMask;
    private javax.swing.JLabel jLabelBeard;
    private javax.swing.JLabel jLabelBeautyspot;
    private javax.swing.JLabel jLabelClose;
    private javax.swing.JLabel jLabelEarring;
    private javax.swing.JLabel jLabelHair;
    private javax.swing.JLabel jLabelHat;
    private javax.swing.JLabel jLabelHeadphones;
    private javax.swing.JLabel jLabelHeadphones1;
    private javax.swing.JLabel jLabelIcon;
    private javax.swing.JLabel jLabelMask;
    private javax.swing.JLabel jLabelMinimize;
    private javax.swing.JLabel jLabelSkincolor;
    private javax.swing.JLabel jLabelSmoking;
    private javax.swing.JLabel jLabelTitel;
    private javax.swing.JPanel jPanelClose;
    private javax.swing.JPanel jPanelMinimize;
    private javax.swing.JLabel lableGoggle;
    private javax.swing.JPanel menuPanel;
    private javax.swing.JPanel topPanel;
    // End of variables declaration//GEN-END:variables
}